name: internal-api 
group: e-shop
replicaCount: 1
minReadySeconds: 120

application:
  track: "" 
  healthcheck: "/health"
  commitId: ""
  branch: ""

affinityEnabled: "false"

resources:
  limits:
    cpu: "300m"
    memory: "0.5Gi"
  requests:
    cpu: "150m"
    memory: "0.5Gi"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  path: api/v1

nodeSelector:
  node-group: prd

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPU: 80