name: internal-api 
group: e-shop
replicaCount: 1
minReadySeconds: 120

application:
  track: "" 
  healthcheck: "/health"
  commitId: ""
  branch: ""

affinityEnabled: "false"

resources:
  limits:
    cpu: "500m"
    memory: "0.7Gi"
  requests:
    cpu: "250m"
    memory: "0.7Gi"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  path: api/v1

nodeSelector:
  node-group: prd

hpa:
  minReplicas: 2
  maxReplicas: 20
  targetCPU: 80